#!/bin/bash
VAULT_RETRIES=5
echo "Vault is starting..."
until vault status > /dev/null 2>&1 || [ "$VAULT_RETRIES" -eq 0 ]; do
        echo "Waiting for vault to start...: $((VAULT_RETRIES--))"
        sleep 1
done
echo "Authenticating to vault..."
vault login token=18456350-7b89-11ed-85e9-a5830358e351
echo "Initializing vault..."
vault secrets enable -version=2 -path=secret kv
echo "Adding entries..."
vault kv put secret/transaction-service cbs.database.url=jdbc:informix-sqli://192.168.202.38:16001/afb300623:informixserver=ol_cbs cbs.database.username=informix cbs.database.password=informix cbs.database.driver=com.informix.jdbc.IfxDriver spring.datasource.url=jdbc:postgresql://172.21.253.246:5432/middleware spring.datasource.username=postgres spring.datasource.password=postgres spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect accounting.booklet.product=110,170 accounting.booklet.posting=true accounting.deposit.codes=001,011,002 accounting.currency.local=001 eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka eureka.instance.preferIpAddress=true eureka.instance.lease-renewal-interval-in-seconds=30 spring.jpa.hibernate.ddl-auto=update spring.jpa.show-sql=true spring.jpa.properties.hibernate.format_sql=true
vault kv put secret/customer-service cbs.database.url=jdbc:informix-sqli://192.168.202.38:16001/afb300623:informixserver=ol_cbs cbs.database.username=informix cbs.database.password=informix cbs.database.driver=com.informix.jdbc.IfxDriver eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka eureka.instance.preferIpAddress=true eureka.instance.lease-renewal-interval-in-seconds=30
vault kv put secret/branch-service cbs.database.url=jdbc:informix-sqli://192.168.202.38:16001/afb300623:informixserver=ol_cbs cbs.database.username=informix cbs.database.password=informix cbs.database.driver=com.informix.jdbc.IfxDriver eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka eureka.instance.preferIpAddress=true eureka.instance.lease-renewal-interval-in-seconds=30
vault kv put secret/teller-service cbs.database.url=jdbc:informix-sqli://192.168.202.38:16001/afb300623:informixserver=ol_cbs cbs.database.username=informix cbs.database.password=informix cbs.database.driver=com.informix.jdbc.IfxDriver eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka eureka.instance.preferIpAddress=true eureka.instance.lease-renewal-interval-in-seconds=30
vault kv put secret/account-service services.datasystemservices.username=informix services.datasystemservices.password=informix services.datasystemservices.url=jdbc:informix-sqli://192.168.202.38:16001/afb300623:informixserver=ol_cbs services.datasystemservices.driver=com.informix.jdbc.IfxDriver services.datasourcesetting.maxActive=20 services.datasourcesetting.maxIdle=20 services.datasourcesetting.minIdle=0 services.datasourcesetting.initialSize=2 services.datasourcesetting.minEvictableIdleTimeMillis=5000 services.datasourcesetting.maxWait=30000 services.datasourcesetting.testOnBorrow=true services.datasourcesetting.validationQuery="select count(*) from bknom" services.datasourcesetting.validationInterval=30000 services.datasourcesetting.timeBetweenEvictionRunsMillis=5000 services.datasourcesetting.removeAbandonedTimeout=3600 services.datasourcesetting.removeAbandoned=true services.datasourcesetting.logAbandoned=false services.datasourcesetting.dialect=org.hibernate.dialect.InformixDialect springdoc.api-docs.path=/account-service/v3/api-docs springdoc.swagger-ui.path=/account-service/swagger-ui.html eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka eureka.instance.preferIpAddress=true eureka.instance.lease-renewal-interval-in-seconds=30 application.compute.agios=985110,985310 application.compute.out.agios=985100,985300 application.outstanding.sms=924100 application.outstanding.avd=924200 application.outstanding.bnf=924300 application.outstanding.rtg=924400 application.outstanding.cdi=924600 application.outstanding.cdo=924700 application.outstanding.avi=924800 application.outstanding.avt=924900 application.outstanding.gft=924500
echo "Complete..."
