#Global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 15s  # scrape_timeout is set to the global default (10s).
# A scrape configuration containing exactly one endpoint to scrape:# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'branch_service'
    metrics_path: '/cbsservices/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']
        labels:
          application: 'Branch Service Application'
  - job_name: 'customer_service'
    metrics_path: '/cbsservices/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8083']
        labels:
          application: 'Customer Service Application'
  - job_name: 'transaction_service'
    metrics_path: '/cbsservices/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']
        labels:
          application: 'Transaction Service Application'
  - job_name: 'account_service'
    metrics_path: '/cbsservices/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8085']
        labels:
          application: 'Account Service Application'
  - job_name: 'teller_service'
    metrics_path: '/cbsservices/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8084']
        labels:
          application: 'Teller Service Application'
